#!/bin/bash
export DOTDIR="$HOME/dotfiles"
export VIMINIT='source $MYVIMRC'
export MYBASHRC="$DOTDIR/bash/bashrc"
export MYVIMRC="$DOTDIR/vim/vimrc.vim"
export MYTMUXCONF="$DOTDIR/tmux/tmux.conf"
export MYEMACSINIT="$DOTDIR/.emacs.d/init.el"

export PATH="$HOME/bin:/usr/local/sbin:$PATH"
export TERM=xterm-256color

# This is GOLD for finding out what is taking so much space on your drives!
alias diskspace="du -S | sort -n -r |more"
# Show me the size (sorted) of only the folders in this directory
alias folders="find . -maxdepth 1 -type d -print | xargs du -sk | sort -rn"

# This is where you put your hand rolled scripts (remember to chmod them)
PS1='\u\w\$ '
[ -z "$PS1" ] && return
function cd {
    builtin cd "$@" && ls -aF
    }
function dc {
    builtin cd "$@"
}

## navigation optimizations ##
alias ..='cd ..'
alias ...='cd ...'

if [[ "$OSTYPE" == "darwin"* ]]; then
    ## Colorize the ls output ##
    alias OS='darwin'
    alias ls='ls -G'
    alias lsa='ls -a'
    alias lsal='ls -alh'
    alias ll='ls -alh'
    alias l.='ls -d .* -G'
    alias l='ls -CFlh'
elif [[ "$OSTYPE" == "win32" ]]; then
    alias ls='ls --color=auto'
    alias lsa='ls -a'
    alias lsl='ls -l'
    alias lsal='ls -alh'
    alias ll='ls -alh'
    alias l.='ls -d .* --color=auto'
    alias lsd='ls -alF | grep /$'
    alias l='ls -CFlh'
fi

alias tmux="tmux -f $MYTMUXCONF"
alias apt-get='sudo apt-get'
alias apt-update='sudo apt-get update && sudo apt-get upgrade'
alias .emacs="$MYEMACSINIT"
alias c='clear'
alias pip='sudo pip3.7'
alias python='python3.7'
